# Add explicit overrides for bad data in airlines and airport country names.
hardcoded_alpha2_values = {
    'ALASKA': 'US',
    'ALASKA PACIFIC': 'US',
    'APPALACHIAN': 'US',
    'ATLANTIC NICARAGUA': 'NI',
    'ATLANTIS CANADA': 'CA',
    'AVEMEX': 'MX',
    'AVIANCA': 'CO',
    'Bolivia': 'BO',
    'Brunei': 'BN',
    'Burma': 'MM',
    'Canadian Territories': 'CA',
    'Cape Verde': 'CV',
    'Congo (Brazzaville)': 'CD',
    'Congo (Kinshasa)': 'CD',
    "Cote d'Ivoire": 'CI',
    'Czech Republic': 'CZ',
    'Democratic Republic of Congo': 'CD',
    'East Timor': 'TP',
    'Falkland Islands': 'FK',
    'Hong Kong': 'HK',
    'Hong Kong SAR of China': 'HK',
    'Iran': 'IR',
    'Ivory Coast': 'CI',
    'Johnston Atoll': 'UM',
    'Lao Peoples Democratic Republic': 'LA',
    'Laos': 'LA',
    'Macao': 'MO',
    'Macau': 'MO',
    'Macedonia': 'MK',
    'Micronesia': 'FM',
    'Midway Islands': 'UM',
    'Moldova': 'MD',
    'Netherland': 'NL',
    'North Korea': 'KP',
    'Republic of the Congo': 'CD',
    'Russia': 'RU',
    'Russia]]': 'RU',
    'SWISSBIRD': 'CH',
    'Somali Republic': 'SO',
    'South Korea': 'KR',
    'Svalbard': 'SJ',
    'Swaziland': 'SZ',
    'Syria': 'SY',
    'Tanzania': 'TZ',
    'UNited Kingdom': 'GB',
    'United Kingdom': 'GB',
    'United States': 'US',
    'Venezuela': 'VE',
    'Vietnam': 'VN',
    'Virgin Islands': 'VI',
    'Wake Island': 'UM',
    'Wallis and Futuna': 'WF',
}
